# Generated by Django 4.0.3 on 2022-03-30 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sendMsg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sendmail', models.EmailField(max_length=254)),
                ('sendsubject', models.CharField(max_length=300)),
                ('sendtext', models.TextField()),
            ],
        ),
    ]
