# Generated by Django 4.0.3 on 2022-03-30 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailapp', '0003_receivemsg'),
    ]

    operations = [
        migrations.CreateModel(
            name='setContacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cusername', models.CharField(max_length=30)),
                ('cemail', models.EmailField(max_length=254)),
            ],
        ),
    ]
