# Generated by Django 4.0.3 on 2022-04-05 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailapp', '0008_setcontacts_caddress_setcontacts_cphonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='usersLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usmail', models.EmailField(max_length=254)),
            ],
        ),
    ]
