# Generated by Django 4.0.3 on 2022-04-05 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailapp', '0009_userslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='setcontacts',
            name='cemailholder',
            field=models.EmailField(default='test@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
