# Generated by Django 4.0.3 on 2022-04-06 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailapp', '0010_setcontacts_cemailholder'),
    ]

    operations = [
        migrations.CreateModel(
            name='walletBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet', models.CharField(max_length=30)),
            ],
        ),
    ]
