# Generated by Django 4.0.3 on 2022-04-06 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailapp', '0013_alter_getprofiledata_ppass_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivemsg',
            name='cruser',
            field=models.EmailField(default='test@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sendmsg',
            name='cruser',
            field=models.EmailField(default='test@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
