# Generated by Django 4.0.3 on 2022-03-30 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailapp', '0004_setcontacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='profileData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choosefile', models.ImageField(upload_to='uploads/')),
                ('pname', models.CharField(max_length=30)),
                ('pmail', models.EmailField(max_length=254)),
                ('pdate', models.DateField()),
                ('pcountry', models.CharField(max_length=30)),
                ('paddress', models.TextField()),
                ('pnumber', models.CharField(max_length=30)),
                ('pprofession', models.CharField(max_length=30)),
                ('ppass', models.CharField(max_length=30)),
                ('prpass', models.CharField(max_length=30)),
                ('pid', models.CharField(max_length=30)),
            ],
        ),
    ]
