# Generated by Django 4.0.3 on 2022-04-03 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailapp', '0006_getprofiledata_delete_profiledata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getprofiledata',
            name='choosefile',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='getprofiledata',
            name='pid',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
