# Generated by Django 4.0.3 on 2022-04-05 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailapp', '0007_alter_getprofiledata_choosefile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setcontacts',
            name='caddress',
            field=models.TextField(default='user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setcontacts',
            name='cphonenumber',
            field=models.CharField(default='user', max_length=13),
            preserve_default=False,
        ),
    ]
