# Generated by Django 4.0.3 on 2022-04-06 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailapp', '0011_walletbalance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletbalance',
            name='id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
